baseURL: "/"
title: "Pytool"
theme: "hugo-theme-hueman"
languageCode: "zh-CN"
hasCJKLanguage: true
copyright: "Copyright (c) 2017. All rights reserved. (版权所有) <a href='http://www.miitbeian.gov.cn/'>鲁ICP备17074587号-1</a>"
# disqusShortname: "rinetd"      # disqus_shortname
googleAnalytics: "UA-106129999-1"      # UA-XXXXXXXX-X

MetaDataFormat: "yaml"
canonifyurls: true
# builddrafts: false
PaginatePath: paginator
disablePathToLower: false     # false -> 路径小写
# if true, use /filename.html instead of /filename/
uglyURLs:                   false

# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax: false
# color-codes for highlighting derived from this style
pygmentsStyle:              "default"
# true use pygments-css or false will color code directly
pygmentsUseClasses:         true


permalinks:
  posts: /:year/:month/:day/:slug/

outputs:
  home:
    - "HTML"
    - "RSS"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

Taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

Author:
  name: "rinetd"
  email: "coderd"

params:
  changyanAppid: "cytgPrsTW"
  changyanAppkey: "prod_a8b514a0c64b034bba38e466be98c266"
  GitHubUser: "pytool"
  SidebarRecentLimit: 5
  DateForm : "2006年01月02日 15:04:05"
  # Tagline: "thinking"
  Description: "如果你没有感觉到时间不够用时，你多半正在虚度光阴。"
  Keywords: "独立博客,程序员,思考,读书笔记,技术分享"

menu:
  main:
      - Name: "归档"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "post"
        URL: "/post/"
      - Name: "关于我"
        Pre: "<i class='fa fa-road'></i>"
        Identifier: "about"
        Weight: -100
        URL: "/about/"

images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
